
services:
  php74:
    build:
      context: .
      dockerfile: Dockerfile-74
    ports:
      - "8074:80"
    volumes:
      - .:/var/www/html:Z
    env_file:
      - .env.local
    depends_on:
      db:
        condition: service_healthy

  # Not needed for now, we will move to it later when the project's laravel version has been updated and tested on php 8.1.
  # php81:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-81
  #   ports:
  #     - "8081:80"
  #   volumes:
  #     - .:/var/www/html:Z
  #   depends_on:
  #     - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myyanga
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 3s
      timeout: 3s
      retries: 20
      start_period: 3s
    volumes:
      - db_data:/var/lib/mysql
      # Uncomment the line below if you have a DB_BACKUP_FILE (.sql) in your .env (docker uses .env by default not .env.local)
      - ${DB_BACKUP_FILE:-./docker/mysql/init.sql}:/docker-entrypoint-initdb.d/init.sql:ro

  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      # Needed to upload large .sql files to the db via phpmyadmin.
      UPLOAD_LIMIT: 20M
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
